trigger:
- main

pool:
  vmImage: "ubuntu-latest"

variables:
  acrLoginServer: $(acr_login_server)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r app/requirements.txt
    pytest app/test_app.py
  displayName: 'Run tests'

  - task: Docker@2
    inputs:
      command: buildAndPush
      repository: $(acrLoginServer)/order-service
      dockerfile: "**/Dockerfile"
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(Build.BuildId)
    displayName: "Build and Push Docker image"
