trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      pytest
    displayName: "Run tests"

  - task: Docker@2
    inputs:
      command: buildAndPush
      repository: your-docker-repository/order-service
      dockerfile: "**/Dockerfile"
      containerRegistry: your-container-registry
      tags: |
        $(Build.BuildId)
    displayName: "Build and Push Docker image"

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(Pipeline.Workspace)"
      artifact: "drop"
    displayName: "Publish Artifact"
