apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: tech-prod
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
