apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: tech-prod
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 9fggrJpMacrdevopsg1.azurecr.io/order-service:33
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "3Gi"
            requests:
              memory: "2Gi"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internal-prod
  namespace: tech-prod
spec:
  podSelector:
    matchLabels:
      app: order-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
